### ISSUE TITLE
[BUG] Problem using Plugwise USB Stick: Rpi hangs due to running out of memory

### ISSUE THREAD

**Issue by MagnusThome** [plugwise/plugwise_usb-beta#10]
### Describe the bug.

Plugwise might be totally innocent but here's my scenario:

Two fully separate HA installations in different houses. Both are Rpi4 with new original Rpi OEM PSUs. Both with Plugwise USB Stick plugged in. Both regularly crash and need power cycling to get back up again. 

In addition to the Plugwise Beta plus Sticks both also have Tasmota installed. Other than that they have a few things installed but not the same on both.

Just curious if the Stick can be part of the problem if anyone else have had issues? And if so if Plugwise beta is something to dig out logs from and so on.

### What version of Home Assistant Core has the issue?

All (both Rpis set up from scratch this spring)

### What was the last working version of Home Assistant Core?

None

### What type of installation are you running?

Home Assistant OS

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

USB: Stick

### What firmware version is your Plugwise product at?

Circles are firmware: 2015-09-18 10:53:15

**Comment by dirixmjm** [comment]
@MagnusThome can you please try with release 0.31.1b1?
see https://github.com/plugwise/plugwise_usb-beta/discussions/110

**Comment by MagnusThome** [comment]
> @MagnusThome can you please try with release 0.31.1b1? see #110

Sorry can't, I've sold off all Plugwise gear.

**Comment by dirixmjm** [comment]
@MagnusThome  ok I understand.
@CoMPaTech  can you please close this one.
