### ISSUE TITLE
[BUG]:  8 - 10 plug out of 25 detected in discovery phase

### ISSUE THREAD

**Issue by joostwestra** [plugwise/plugwise_usb-beta#12]
### Describe the bug.

Only a portion of the plugs are detected. Looking at the logs it appears to be a timing and logic issue.

What appears to be happening is that on first discovery the plug do not al reply on time (probably that total timeout is too short).

A retry does not happen "to speed up discovery"

And then because the types are not yet known they are automatically assumed to be battery operated devices (which they are not).

The result later is that they are never picked up.

(the same network does work with OpenHab)

### What version of Home Assistant Core has the issue?

2023.2.5

### What was the last working version of Home Assistant Core?

none

### What type of installation are you running?

Home Assistant Container

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

USB: Stick

### What firmware version is your Plugwise product at?

2011-05-13 09:17:07

### Diagnostics information

When trying to reproproduce It appears I even get a timing problem with added the circle+:

[home-assistant_plugwise_2023-02-17T09-19-46.296Z.log](https://github.com/plugwise/plugwise-beta/files/10765158/home-assistant_plugwise_2023-02-17T09-19-46.296Z.log)

### Additional information

I did a number of complete integration reinstalls:

First try: 10 Plugs
second try: 8 plugs
3 : no circle +
4 : no circle +
5 : no circle +

I am quite comfortable modifying python code and constant if you can give me a pointer on the dependencies.

**Comment by joostwestra** [comment]
Did a new deployment today.
Again many of the powered up plugs were not detected.
FIX:
Go to plugwise source and make sure ALL! the plugs are available in the Source Application. If you powered up en need less plug make sure you remove them form the network.
Now remove and reinstall the integration an all plugs are detected.

**Comment by dirixmjm** [comment]
@joostwestra although I don't expect the problem to be solved, could you please try with beta-version 0.40.5a1 and report back?
To avoid a huge logfile, please set loglevel to info (that should enable sufficient data to get started).

```
logger:
  default: warning
  logs:
    custom_components.plugwise_usb: info
    plugwise_usb: info
```

**Comment by joostwestra** [comment]
@dirixmjm Good to see you are picking this up. It might take while for me to test this, because I am currently using the system with a smaller deployment and less "hops" that work more stable.

**Comment by bouwew** [comment]
@joostwestra Are you still using Plugwise_USB-beta?
If yes, please test v0.50.0a20

**Comment by joostwestra** [comment]
I am currently using a smaller setup that works fine. If I have time I could test a bigger setup again if you think there are improvements.

**Comment by bouwew** [comment]
Also, in HA, the Stick is shown as the `via_device` and more device data is shown.
All in all a huge improvement.

**Comment by bouwew** [comment]
But, of course, your decision :)
