### ISSUE TITLE
[QUESTION]: Best way to migrate to USB beta?

### ISSUE THREAD

**Issue by MagnusThome** [plugwise/plugwise_usb-beta#21]
### Describe the solution you are looking for

I just tested installing the plugwise USB beta (after actually only disabling the plugwise beta) and it found all the circles 👍 Is this the correct way?

Secondly, where are all the circle names, sensor names and area settings stored? Is there any way to copy this over instead of manually editing each circle in the HA web GUI from scratch?

Thanks!

### What type of installation are you running?

Home Assistant OS

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

USB: Stick

### What firmware version is your Plugwise product at?

Latest

### Your setup

......

**Comment by bouwew** [comment]
The entity-data can be found in the file `config\.storage\core.entity_registry`
Search for `plugwise` in this file, there will be many entries!

**Comment by MagnusThome** [comment]
Thank you!
