### ISSUE TITLE
[BUG]: Set a new state of the switch only working after a restart of HA.

### ISSUE THREAD

**Issue by herwinjan** [plugwise/plugwise_usb-beta#46]
### Describe the bug.

In the lasttest version, de switching is working again, but stop after a couple of hours.

This is also noticeable on the measurements of the energy readings. See attached graph, the arrows: First one is the update/restart of HA and the second one is the moment the measurement is stopping regularly updating. At 5 AM I restarted HA again and the readings become normal again.

![CleanShot 2023-08-07 at 18 58 01@2x](https://github.com/plugwise/plugwise_usb-beta/assets/11133888/fba2337d-d7de-4e04-bff4-d31316e0e75c)

And we have a memory leak again after a couple of switches.

### What version of Plugwise Beta are you using?

lastes

### What was the last working version of Plugwise Beta (or Core if not using beta before)?

lastes

### What version of Home Assistant Core are you using?

latest

### What type of installation are you running?

Home Assistant OS

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

USB: Stick

### What firmware version is your Plugwise product at?

2011-06-27 10:52:18

**Comment by dirixmjm** [comment]
@herwinjan  can you try the following and report your result?
https://github.com/plugwise/plugwise_usb-beta/issues/67#issuecomment-1871858557

**Comment by herwinjan** [comment]
yes, start testing today!

**Comment by dirixmjm** [comment]
Closing, as this is basically the same issue as https://github.com/plugwise/plugwise_usb-beta/issues/57, it is sufficient to keep one issue open.
