### ISSUE TITLE
[FEATURE]: Add brand icon/logo

### ISSUE THREAD

**Issue by mvdwetering** [plugwise/plugwise_usb-beta#54]
### Describe the solution you are looking for

This integration shows no icon in the integrations overview and broken icons in the devices list
![image](https://github.com/plugwise/plugwise_usb-beta/assets/732514/f9e8892b-70a2-499f-bdf0-6ecdcff99be0)
![image](https://github.com/plugwise/plugwise_usb-beta/assets/732514/381cff90-dff6-48be-b400-ae06b8eec1f5)

Would be nice to add an icon/logo for it. 
Adding an icon/logo can be done with a PR at https://github.com/home-assistant/brands

### Is your feature request related to a problem? (optional)

Not really, just visually not great.

### What type of installation are you running?

Home Assistant OS

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

USB: Stick

### What firmware version is your Plugwise product at?

n.a.

### Your setup

n.a.

### Additional context

I thought about making a PR myself, but not sure which icon/logo to use.

**Comment by CoMPaTech** [comment]
It's somewhat of something we knew would happen and hoped to avoid with timely matters; e.g. the idea was/is to have a plugwise brand with both Networked and USB 'below' it, just like for instance the Amazon brand with various AWS services. That way no rebranding would have been necessary. Given the fact that said progress is not as fluent as foreseen it might be good to duplicate the brand for USB so it shows again.

As for choices, I think just duplicating the logo would suffice (it's a matter of 'resolving' the integration name to a png file)

**Comment by brefra** [comment]
As this is specific to the legacy USB stick I suggest to use the legacy logo of the original windows "source" software too.

**Comment by CoMPaTech** [comment]
@mvdwetering @brefra I'd say have a go at it, instructions for adding them for custom integrations is readily available at https://github.com/home-assistant/brands or if the old plugwise_stick still apply just rename them accordingly to plugwise_usb-beta

**Comment by brefra** [comment]
The logo files have been updated by the associated PR above.
