### ISSUE TITLE
[BUG] Not all entities of a Circle seem to have valid values yet.

### ISSUE THREAD

**Issue by CoHoAppel** [plugwise/plugwise_usb-beta#7]
My configuration: USB Stick, Circle+ and 6 more Circles. Latest version 0.14.4 installed. The configuration runs stable and a number of entities (switching on/off; current power usage; power consumption current hour;) work well, however the values of power consumption previous hour; power consumption today /yesterday; on the overview screen remain empty. Are these still work in progress? I checked the Plugwise part by moving the the stick to a Windows PC and "reading" the history with the Plugwise Source application. All connected Circles reported the power-history of the past couple of weeks.

**Comment by dirixmjm** [comment]
@CoMPaTech  @bouwew  can this be closed?

**Comment by dirixmjm** [comment]
Closing due to no further response. Please open a new ticket if the problem persists with version 0.40.5a1 (enable beta testing).
