### ISSUE TITLE
[BUG] Only 25 plugs discovered and I have 34 plugs

### ISSUE THREAD

**Issue by Lululef** [plugwise/plugwise_usb-beta#8]
I installed the latest version of plugwise-beta. I have a stick usb, circle+, and 35 plugs.  In plugwise source, I see all the plugs. In Home assistant in the beginning, the program found 17 plugs, and then it progressed to 25 plugs. Now it's stuck on 25 for 2 days. Should I just wait or is 25 maybe the limit of the plugin. It's great that some people are willing to put some effort in devlopping programs. Can I do something else to help? I am new to all this.

**Comment by dirixmjm** [comment]
Please try with v0.40.5 and provide a new issue report if this problem persists.
